In [2]:
import numpy as np
N = 2
p_cara = np.array([0.5,0.8, 0.3])
p_priori = np.array([0.8, 0.1, 0.1]) # prob de que sea tipo 1

#x = np.random.choice(N+1, size= 3, p=p_priori) # agarro una moneda de 0,1,2 con prob 0.1,0.2,0.7
moneda = np.random.choice([0,1,2], p =np.ndarray.tolist(p_priori)) # AGARRO UNA MONEDA y depsues la tiro un monton de veces

p_post = p_priori.copy()
print(p_post)
for i in range(10):
    #en cada paso actualizo la prob a posteriori
    px = p_cara[moneda] # probabilidad de haber agarrado la moneda
    lado = np.random.choice([0,1], p=[1-px,px]) # tiro y tiro 
    if lado: # si sale cara
        p_post *= p_cara # p_cara dado el tipo
    else:
        p_post *= 1-p_cara
    norm = np.sum(p_post)
    p_post /= norm
    print(p_post) # esto es la prob de que sea tipo dado cara

# el problema con esto es la probabilidad se puede cagar en el sentido de precision 

[0.8 0.1 0.1]
[0.81632653 0.04081633 0.14285714]
[0.84388186 0.06751055 0.08860759]
[0.84817642 0.02714165 0.12468193]
[0.82061382 0.01050386 0.16888232]
[0.87415644 0.01790272 0.10794084]
[0.90345989 0.02960457 0.06693554]
[0.8953911  0.01173607 0.09287283]
[0.92318591 0.01936061 0.05745348]
[0.91281178 0.00765722 0.079531  ]
[0.88862512 0.00298173 0.10839314]
